version: '3.4'

services:
  fbm_etl:
    build: "./etl"
    depends_on:
    - "fbm_db"
    links:
    - fbm_db:fbm_db

  fbm_db:
    image: mysql/mysql-server:5.7
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports: 
      - "3306:3306"
    environment:
      MYSQL_DATABASE: facebook_messenger
      MYSQL_USER: jeremy
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  fbm_api:
    build: "./api"
    depends_on:
      - "fbm_etl"
    links:
      - fbm_db:fbm_db
    ports:
      - "7000:7000"

  # for local development
  api_render:
    build:
      context: ./front
      target: 'develop-stage'
    ports:
    - '8080:8080'
    volumes:
    - '.:/app'
    command: /bin/sh -c "npm run serve"
